In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv('titanic_data.csv')
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [12]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",0,-0.204852,0,0,A.5. 3236,-0.493455,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",1,0.740881,0,0,PC 17758,1.314435,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",0,0.701476,0,0,SOTON/O.Q. 3101262,-0.507796,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",0,-0.204852,0,0,359309,-0.493455,NaN,S
417,1309,0,3,"Peter, Master. Michael J",0,-0.204852,1,1,2668,-0.236957,NaN,C

In [13]:
df.shape

(418, 12)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    int64
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         418 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(6), str(4)
memory usage: 39.3 KB

In [16]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,418.000000,418.000000,418.000000,418,418.000000,4.180000e+02,418.000000,418.000000,418,4.180000e+02,91,418
unique,NaN,NaN,NaN,418,NaN,NaN,NaN,NaN,363,NaN,76,3
top,NaN,NaN,NaN,"Kelly, Mr. James",NaN,NaN,NaN,NaN,PC 17608,NaN,B57 B59 B63 B66,S
freq,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,5,NaN,3,270
mean,1100.500000,0.363636,2.265550,NaN,0.363636,5.524555e-17,0.447368,0.392344,NaN,8.711798e-17,NaN,NaN
std,120.810458,0.481622,0.841838,NaN,0.481622,1.001198e+00,0.896760,0.981429,NaN,1.001198e+00,NaN,NaN
min,892.000000,0.000000,1.000000,NaN,0.000000,-2.319355e+00,0.000000,0.000000,NaN,-6.377637e-01,NaN,NaN
25%,996.250000,0.000000,1.000000,NaN,0.000000,-5.200968e-01,0.000000,0.000000,NaN,-4.962194e-01,NaN,NaN
50%,1100.500000,0.000000,3.000000,NaN,0.000000,-2.048523e-01,0.000000,0.000000,NaN,-3.786501e-01,NaN,NaN
75%,1204.750000,1.000000,3.000000,NaN,1.000000,4.847449e-01,1.000000,0.000000,NaN,-7.358230e-02,NaN,NaN
max,1309.000000,1.000000,3.000000,NaN,1.000000,3.656893e+00,8.000000,9.000000,NaN,8.546519e+00,NaN,NaN

In [17]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
413,False,False,False,False,False,False,False,False,False,False,True,False
414,False,False,False,False,False,False,False,False,False,False,False,False
415,False,False,False,False,False,False,False,False,False,False,True,False
416,False,False,False,False,False,False,False,False,False,False,True,False
417,False,False,False,False,False,False,False,False,False,False,True,False

In [18]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [21]:
df=df.drop_duplicates()
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name  Sex       Age  SibSp  \
0                                Kelly, Mr. James    0  0.386231      0
1                Wilkes, Mrs. James (Ellen Needs)    1  1.371370      1
2                       Myles, Mr. Thomas Francis    0  2.553537      0
3                                Wirz, Mr. Albert    0 -0.204852      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1 -0.598908      1
..                                            ...  ...       ...    ...
413                            Spector, Mr. Woolf    0 -0.204852      0
414                  Oliva y Ocana, Dona. Fermina    1  0.740881      0
415                  Saether, Mr. Simon Sivertsen    0  0.701476      0
416                           Ware, Mr. Frederick    0 -0.204852      0
417                      Peter, Master. Michael J    0 -0.204852      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911 -0.497413   NaN        Q
1        0              363272 -0.512278   NaN        S
2        0              240276 -0.464100   NaN        Q
3        0              315154 -0.482475   NaN        S
4        1             3101298 -0.417492   NaN        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236 -0.493455   NaN        S
414      0            PC 17758  1.314435  C105        C
415      0  SOTON/O.Q. 3101262 -0.507796   NaN        S
416      0              359309 -0.493455   NaN        S
417      1                2668 -0.236957   NaN        C

[418 rows x 12 columns]

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].median())
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male  27.0      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male  27.0      0      0
417                      Peter, Master. Michael J    male  27.0      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [22]:
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name  Sex       Age  SibSp  \
0                                Kelly, Mr. James    0  0.386231      0
1                Wilkes, Mrs. James (Ellen Needs)    1  1.371370      1
2                       Myles, Mr. Thomas Francis    0  2.553537      0
3                                Wirz, Mr. Albert    0 -0.204852      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1 -0.598908      1
..                                            ...  ...       ...    ...
413                            Spector, Mr. Woolf    0 -0.204852      0
414                  Oliva y Ocana, Dona. Fermina    1  0.740881      0
415                  Saether, Mr. Simon Sivertsen    0  0.701476      0
416                           Ware, Mr. Frederick    0 -0.204852      0
417                      Peter, Master. Michael J    0 -0.204852      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911 -0.497413   NaN        Q
1        0              363272 -0.512278   NaN        S
2        0              240276 -0.464100   NaN        Q
3        0              315154 -0.482475   NaN        S
4        1             3101298 -0.417492   NaN        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236 -0.493455   NaN        S
414      0            PC 17758  1.314435  C105        C
415      0  SOTON/O.Q. 3101262 -0.507796   NaN        S
416      0              359309 -0.493455   NaN        S
417      1                2668 -0.236957   NaN        C

[418 rows x 12 columns]

In [24]:
df['Age']=df['Age'].astype(int)
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name  Sex  Age  SibSp  Parch  \
0                                Kelly, Mr. James  NaN    0      0      0
1                Wilkes, Mrs. James (Ellen Needs)  NaN    1      1      0
2                       Myles, Mr. Thomas Francis  NaN    2      0      0
3                                Wirz, Mr. Albert  NaN    0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  NaN    0      1      1
..                                            ...  ...  ...    ...    ...
413                            Spector, Mr. Woolf  NaN    0      0      0
414                  Oliva y Ocana, Dona. Fermina  NaN    0      0      0
415                  Saether, Mr. Simon Sivertsen  NaN    0      0      0
416                           Ware, Mr. Frederick  NaN    0      0      0
417                      Peter, Master. Michael J  NaN    0      1      1

                 Ticket      Fare Cabin Embarked
0                330911 -0.497413   NaN        Q
1                363272 -0.512278   NaN        S
2                240276 -0.464100   NaN        Q
3                315154 -0.482475   NaN        S
4               3101298 -0.417492   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236 -0.493455   NaN        S
414            PC 17758  1.314435  C105        C
415  SOTON/O.Q. 3101262 -0.507796   NaN        S
416              359309 -0.493455   NaN        S
417                2668 -0.236957   NaN        C

[418 rows x 12 columns]

In [25]:
df['Fare']=df['Fare'].astype(int)
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name  Sex  Age  SibSp  Parch  \
0                                Kelly, Mr. James  NaN    0      0      0
1                Wilkes, Mrs. James (Ellen Needs)  NaN    1      1      0
2                       Myles, Mr. Thomas Francis  NaN    2      0      0
3                                Wirz, Mr. Albert  NaN    0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  NaN    0      1      1
..                                            ...  ...  ...    ...    ...
413                            Spector, Mr. Woolf  NaN    0      0      0
414                  Oliva y Ocana, Dona. Fermina  NaN    0      0      0
415                  Saether, Mr. Simon Sivertsen  NaN    0      0      0
416                           Ware, Mr. Frederick  NaN    0      0      0
417                      Peter, Master. Michael J  NaN    0      1      1

                 Ticket  Fare Cabin Embarked
0                330911     0   NaN        Q
1                363272     0   NaN        S
2                240276     0   NaN        Q
3                315154     0   NaN        S
4               3101298     0   NaN        S
..                  ...   ...   ...      ...
413           A.5. 3236     0   NaN        S
414            PC 17758     1  C105        C
415  SOTON/O.Q. 3101262     0   NaN        S
416              359309     0   NaN        S
417                2668     0   NaN        C

[418 rows x 12 columns]

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          0 non-null      float64
 5   Age          418 non-null    int64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         418 non-null    int64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(1), int64(7), str(4)
memory usage: 39.3 KB

In [23]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name  Sex       Age  SibSp  \
0                                Kelly, Mr. James  NaN  0.386231      0
1                Wilkes, Mrs. James (Ellen Needs)  NaN  1.371370      1
2                       Myles, Mr. Thomas Francis  NaN  2.553537      0
3                                Wirz, Mr. Albert  NaN -0.204852      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  NaN -0.598908      1
..                                            ...  ...       ...    ...
413                            Spector, Mr. Woolf  NaN -0.204852      0
414                  Oliva y Ocana, Dona. Fermina  NaN  0.740881      0
415                  Saether, Mr. Simon Sivertsen  NaN  0.701476      0
416                           Ware, Mr. Frederick  NaN -0.204852      0
417                      Peter, Master. Michael J  NaN -0.204852      1

     Parch              Ticket      Fare Cabin Embarked
0        0              330911 -0.497413   NaN        Q
1        0              363272 -0.512278   NaN        S
2        0              240276 -0.464100   NaN        Q
3        0              315154 -0.482475   NaN        S
4        1             3101298 -0.417492   NaN        S
..     ...                 ...       ...   ...      ...
413      0           A.5. 3236 -0.493455   NaN        S
414      0            PC 17758  1.314435  C105        C
415      0  SOTON/O.Q. 3101262 -0.507796   NaN        S
416      0              359309 -0.493455   NaN        S
417      1                2668 -0.236957   NaN        C

[418 rows x 12 columns]

In [8]:
pd.get_dummies(df)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,"Name_Abbott, Master. Eugene Joseph","Name_Abelseth, Miss. Karen Marie","Name_Abelseth, Mr. Olaus Jorgensen",...,Cabin_F E46,Cabin_F E57,Cabin_F G63,Cabin_F2,Cabin_F33,Cabin_F4,Cabin_G6,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,34.5,0,0,7.8292,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,893,1,3,47.0,1,0,7.0000,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,894,0,2,62.0,0,0,9.6875,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,895,0,3,27.0,0,0,8.6625,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,896,1,3,22.0,1,1,12.2875,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,27.0,0,0,8.0500,False,False,False,...,False,False,False,False,False,False,False,False,False,True
414,1306,1,1,39.0,0,0,108.9000,False,False,False,...,False,False,False,False,False,False,False,True,False,False
415,1307,0,3,38.5,0,0,7.2500,False,False,False,...,False,False,False,False,False,False,False,False,False,True
416,1308,0,3,27.0,0,0,8.0500,False,False,False,...,False,False,False,False,False,False,False,False,False,True
417,1309,0,3,27.0,1,1,22.3583,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [31]:
df["Age.scaled"]=(df["Age"]-df["Age"].mean())/df["Age"].std()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age.scaled,Fare.scaled
0,892,0,3,"Kelly, Mr. James",NaN,0,0,0,330911,0,NaN,Q,-0.159315,-0.250081
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",NaN,1,1,0,363272,0,NaN,S,1.257568,-0.250081
2,894,0,2,"Myles, Mr. Thomas Francis",NaN,2,0,0,240276,0,NaN,Q,2.674450,-0.250081
3,895,0,3,"Wirz, Mr. Albert",NaN,0,0,0,315154,0,NaN,S,-0.159315,-0.250081
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",NaN,0,1,1,3101298,0,NaN,S,-0.159315,-0.250081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",NaN,0,0,0,A.5. 3236,0,NaN,S,-0.159315,-0.250081
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",NaN,0,0,0,PC 17758,1,C105,C,-0.159315,0.979728
415,1307,0,3,"Saether, Mr. Simon Sivertsen",NaN,0,0,0,SOTON/O.Q. 3101262,0,NaN,S,-0.159315,-0.250081
416,1308,0,3,"Ware, Mr. Frederick",NaN,0,0,0,359309,0,NaN,S,-0.159315,-0.250081
417,1309,0,3,"Peter, Master. Michael J",NaN,0,1,1,2668,0,NaN,C,-0.159315,-0.250081

In [32]:
df["Fare.scaled"]=(df["Fare"]-df["Fare"].mean())/df["Fare"].std()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age.scaled,Fare.scaled
0,892,0,3,"Kelly, Mr. James",NaN,0,0,0,330911,0,NaN,Q,-0.159315,-0.250081
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",NaN,1,1,0,363272,0,NaN,S,1.257568,-0.250081
2,894,0,2,"Myles, Mr. Thomas Francis",NaN,2,0,0,240276,0,NaN,Q,2.674450,-0.250081
3,895,0,3,"Wirz, Mr. Albert",NaN,0,0,0,315154,0,NaN,S,-0.159315,-0.250081
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",NaN,0,1,1,3101298,0,NaN,S,-0.159315,-0.250081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",NaN,0,0,0,A.5. 3236,0,NaN,S,-0.159315,-0.250081
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",NaN,0,0,0,PC 17758,1,C105,C,-0.159315,0.979728
415,1307,0,3,"Saether, Mr. Simon Sivertsen",NaN,0,0,0,SOTON/O.Q. 3101262,0,NaN,S,-0.159315,-0.250081
416,1308,0,3,"Ware, Mr. Frederick",NaN,0,0,0,359309,0,NaN,S,-0.159315,-0.250081
417,1309,0,3,"Peter, Master. Michael J",NaN,0,1,1,2668,0,NaN,C,-0.159315,-0.250081

In [33]:
df["Fare_norm"]=(df["Fare"]-df["Fare"].min())/df["Fare"].max()-df["Fare"].min()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age.scaled,Fare.scaled,Fare_norm
0,892,0,3,"Kelly, Mr. James",NaN,0,0,0,330911,0,NaN,Q,-0.159315,-0.250081,0.000
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",NaN,1,1,0,363272,0,NaN,S,1.257568,-0.250081,0.000
2,894,0,2,"Myles, Mr. Thomas Francis",NaN,2,0,0,240276,0,NaN,Q,2.674450,-0.250081,0.000
3,895,0,3,"Wirz, Mr. Albert",NaN,0,0,0,315154,0,NaN,S,-0.159315,-0.250081,0.000
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",NaN,0,1,1,3101298,0,NaN,S,-0.159315,-0.250081,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",NaN,0,0,0,A.5. 3236,0,NaN,S,-0.159315,-0.250081,0.000
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",NaN,0,0,0,PC 17758,1,C105,C,-0.159315,0.979728,0.125
415,1307,0,3,"Saether, Mr. Simon Sivertsen",NaN,0,0,0,SOTON/O.Q. 3101262,0,NaN,S,-0.159315,-0.250081,0.000
416,1308,0,3,"Ware, Mr. Frederick",NaN,0,0,0,359309,0,NaN,S,-0.159315,-0.250081,0.000
417,1309,0,3,"Peter, Master. Michael J",NaN,0,1,1,2668,0,NaN,C,-0.159315,-0.250081,0.000

In [34]:
df["Age_norm"]=(df["Age"]-df["Age"].min())/df["Age"].max()-df["Age"].min()
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age.scaled,Fare.scaled,Fare_norm,Age_norm
0,892,0,3,"Kelly, Mr. James",NaN,0,0,0,330911,0,NaN,Q,-0.159315,-0.250081,0.000,2.666667
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",NaN,1,1,0,363272,0,NaN,S,1.257568,-0.250081,0.000,3.000000
2,894,0,2,"Myles, Mr. Thomas Francis",NaN,2,0,0,240276,0,NaN,Q,2.674450,-0.250081,0.000,3.333333
3,895,0,3,"Wirz, Mr. Albert",NaN,0,0,0,315154,0,NaN,S,-0.159315,-0.250081,0.000,2.666667
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",NaN,0,1,1,3101298,0,NaN,S,-0.159315,-0.250081,0.000,2.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",NaN,0,0,0,A.5. 3236,0,NaN,S,-0.159315,-0.250081,0.000,2.666667
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",NaN,0,0,0,PC 17758,1,C105,C,-0.159315,0.979728,0.125,2.666667
415,1307,0,3,"Saether, Mr. Simon Sivertsen",NaN,0,0,0,SOTON/O.Q. 3101262,0,NaN,S,-0.159315,-0.250081,0.000,2.666667
416,1308,0,3,"Ware, Mr. Frederick",NaN,0,0,0,359309,0,NaN,S,-0.159315,-0.250081,0.000,2.666667
417,1309,0,3,"Peter, Master. Michael J",NaN,0,1,1,2668,0,NaN,C,-0.159315,-0.250081,0.000,2.666667

In [ ]:
Q1=df["Fare"].quantile(0.25)
Q3=df["Fare"].quantile(0.75)
IQR=Q3-Q1
df=df[(df["Fare"]

In [11]:
scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])
print(df.head())

   PassengerId  Survived  Pclass  \
0          892         0       3
1          893         1       3
2          894         0       2
3          895         0       3
4          896         1       3

                                           Name  Sex       Age  SibSp  Parch  \
0                              Kelly, Mr. James    0  0.386231      0      0
1              Wilkes, Mrs. James (Ellen Needs)    1  1.371370      1      0
2                     Myles, Mr. Thomas Francis    0  2.553537      0      0
3                              Wirz, Mr. Albert    0 -0.204852      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1 -0.598908      1      1

    Ticket      Fare Cabin Embarked
0   330911 -0.497413   NaN        Q
1   363272 -0.512278   NaN        S
2   240276 -0.464100   NaN        Q
3   315154 -0.482475   NaN        S
4  3101298 -0.417492   NaN        S